currency:
  api-url: https://openexchangerates.org/api
  api-key: 88fea2b30a2f42e19ea4791d5a5fd4e2
  default-currency-code: RUB
gif:
  api-url: https://api.giphy.com/v1/gifs
  api-key: XMQuNiCos2elVLLIW7yYJAkO3K4JPpwH
  rating: g
  lang: en